version: 2

mkdocs:
  configuration: mkdocs.yml

python:
  version: 3.6
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt

# Set the version of Python
build:
  os: ubuntu-20.04  # <- add this line
  tools:
    python: "3.10"
