site_name: NGINX Extras docs
site_description: "Automatic documentation from sources, for NGINX Extras."
site_url: https://www.getpagespeed.com/nginx-extras
theme:
  name: "material"
  palette:
    scheme: slate
    primary: teal
    accent: purple
  features:
    - navigation.expand
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("docs")
          selection:
            new_path_syntax: yes
      watch:
        - lastversion
nav:
  - Overview: index.md
  - Modules:
    - lastversion.py: reference/lastversion.md
    - Version.py: reference/Version.md
  - 'RPM repository': 'https://www.getpagespeed.com/posts'
markdown_extensions:
  - admonition
  - markdown_include.include
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.snippets:
      check_paths: true
  - toc:
      permalink: "¤"
extra:
  generator: false