extra:
  analytics:
    property: UA-51252096-1
    provider: google
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - abbr
  - admonition
  - markdown_include.include
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - attr_list
  - pymdownx.snippets:
      check_paths: true
nav:
- 'Overview': index.md
- Modules:
  - accept-language: modules/accept-language.md
  - ajp: modules/ajp.md
  - array-var: modules/array-var.md
  - auth-ldap: modules/auth-ldap.md
  - auth-pam: modules/auth-pam.md
  - aws-auth: modules/aws-auth.md
  - bot-verifier: modules/bot-verifier.md
  - brotli: modules/brotli.md
  - cache-purge: modules/cache-purge.md
  - captcha: modules/captcha.md
  - combined-upstreams: modules/combined-upstreams.md
  - concat: modules/concat.md
  - cookie-flag: modules/cookie-flag.md
  - cookie-limit: modules/cookie-limit.md
  - coolkit: modules/coolkit.md
  - doh: modules/doh.md
  - dynamic-etag: modules/dynamic-etag.md
  - dynamic-limit-req: modules/dynamic-limit-req.md
  - echo: modules/echo.md
  - encrypted-session: modules/encrypted-session.md
  - execute: modules/execute.md
  - f4fhds: modules/f4fhds.md
  - fancyindex: modules/fancyindex.md
  - fips-check: modules/fips-check.md
  - flv: modules/flv.md
  - form-input: modules/form-input.md
  - geoip: modules/geoip.md
  - geoip2: modules/geoip2.md
  - google: modules/google.md
  - graphite: modules/graphite.md
  - headers-more: modules/headers-more.md
  - hmac-secure-link: modules/hmac-secure-link.md
  - html-sanitize: modules/html-sanitize.md
  - iconv: modules/iconv.md
  - image-filter: modules/image-filter.md
  - immutable: modules/immutable.md
  - ipscrub: modules/ipscrub.md
  - jpeg: modules/jpeg.md
  - js-challenge: modules/js-challenge.md
  - json-var: modules/json-var.md
  - jwt: modules/jwt.md
  - length-hiding: modules/length-hiding.md
  - log-zmq: modules/log-zmq.md
  - lua: modules/lua.md
  - memc: modules/memc.md
  - naxsi: modules/naxsi.md
  - nchan: modules/nchan.md
  - ndk: modules/ndk.md
  - njs: modules/njs.md
  - pagespeed: modules/pagespeed.md
  - passenger: modules/passenger.md
  - perl: modules/perl.md
  - phantom-token: modules/phantom-token.md
  - postgres: modules/postgres.md
  - pta: modules/pta.md
  - push-stream: modules/push-stream.md
  - rdns: modules/rdns.md
  - redis2: modules/redis2.md
  - rtmp: modules/rtmp.md
  - secure-token: modules/secure-token.md
  - security: modules/security.md
  - security-headers: modules/security-headers.md
  - set-misc: modules/set-misc.md
  - shibboleth: modules/shibboleth.md
  - slowfs: modules/slowfs.md
  - small-light: modules/small-light.md
  - srcache: modules/srcache.md
  - statsd: modules/statsd.md
  - sticky: modules/sticky.md
  - stream-lua: modules/stream-lua.md
  - stream-upsync: modules/stream-upsync.md
  - substitutions: modules/substitutions.md
  - sysguard: modules/sysguard.md
  - testcookie: modules/testcookie.md
  - traffic-accounting: modules/traffic-accounting.md
  - ts: modules/ts.md
  - untar: modules/untar.md
  - upload: modules/upload.md
  - upstream-fair: modules/upstream-fair.md
  - upsync: modules/upsync.md
  - vts: modules/vts.md
  - webp: modules/webp.md
  - xslt: modules/xslt.md
  - zip: modules/zip.md
- Lua Scripting: lua-scripting.md
- Distributions:
  - branches.md
  - nginx-mod.md
  - tengine.md
  - plesk.md
- RPM Repository: https://www.getpagespeed.com/redhat
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        selection:
          new_path_syntax: true
        setup_commands:
        - import sys
        - sys.path.append("docs")
site_description: Automatic documentation from sources, for NGINX Extras.
site_name: NGINX Extras Documentation
site_url: https://nginx-extras.getpagespeed.com/
theme:
  #icon:
  #  logo: bootstrap/box2-fill
  custom_dir: overrides
  features:
    - navigation.expand
    - navigation.top
    - navigation.tabs
    - search.suggest
  logo: assets/nginx-logo.png
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      # accent: purple
      # primary: teal
      scheme: getpagespeed
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
